export const confiteria = [
  //  COMBOS
  {
    id: 1,
    nombre: "Combo Tron Ares Premium",
    tipo: "Combos",
    valor: 32000,
    promocion: "Incluye crispetas grandes + bebida grande + vaso coleccionable Tron Ares",
    imagen: new URL('@/assets/combotron.jpg', import.meta.url).href,
  },
  {
    id: 2,
    nombre: "Combo Halloween",
    tipo: "Combos",
    valor: 30000,
    promocion: "Crispetas medianas + bebida mediana + dulces temáticos",
    imagen: new URL('@/assets/combodracula.jpg', import.meta.url).href,
  },
  {
    id: 3,
    nombre: "Combo Toy Story",
    tipo: "Combos",
    valor: 28000,
    promocion: "Crispetas grandes + bebida grande + vaso coleccionable Toy Story",
    imagen: new URL('@/assets/combotoystory.jpg', import.meta.url).href
  },
  {
    id: 4,
    nombre: "Combo Demon Slayer",
    tipo: "Combos",
    valor: 29000,
    promocion: "Crispetas medianas + bebida grande + vaso coleccionable Demon Slayer",
    imagen: new URL('@/assets/combodemonslayer.jpg', import.meta.url).href,
  },
  {
    id: 5,
    nombre: "Combo Pareja",
    tipo: "Combos",
    valor: 38000,
    promocion: "2 bebidas medianas + crispetas grandes",
    imagen: new URL('@/assets/combopareja.jpeg', import.meta.url).href,
  },
  {
    id: 6,
    nombre: "Combo Familiar",
    tipo: "Combos",
    valor: 55000,
    promocion: "4 bebidas medianas + crispetas extra grandes + 2 snacks",
    imagen: new URL('@/assets/combofamiliar.jpeg', import.meta.url).href,
  },
  {
    id: 7,
    nombre: "Combo Kids",
    tipo: "Combos",
    valor: 20000,
    promocion: "Crispetas pequeñas + jugo + sorpresa",
    imagen: new URL('@/assets/comboinfantil.jpeg', import.meta.url).href,
  },
  {
    id: 8,
    nombre: "Combo Personal",
    tipo: "Combos",
    valor: 18000,
    promocion: "Crispetas medianas + bebida pequeña",
    imagen: new URL('@/assets/palomitas.jpeg', import.meta.url).href,
  },

  //  CRISPETAS
  {
    id: 9,
    nombre: "Crispetas Grandes",
    tipo: "Crispetas",
    valor: 16000,
    promocion: "Porción grande ideal para compartir",
    imagen: new URL('@/assets//crispetagrande.jpg', import.meta.url).href,
  },
  {
    id: 10,
    nombre: "Crispetas Medianas",
    tipo: "Crispetas",
    valor: 13000,
    promocion: "Porción mediana para disfrutar solo o acompañado",
    imagen: new URL('@/assets/crispetasmedianas.jpg', import.meta.url).href,
  },
  {
    id: 11,
    nombre: "Crispetas Pequeñas",
    tipo: "Crispetas",
    valor: 10000,
    promocion: "Porción pequeña ideal para niños",
    imagen: new URL('@/assets/crispetaspequeñas.jpg', import.meta.url).href,
  },

  //  BEBIDAS
  {
    id: 12,
    nombre: "Icee Slush",
    tipo: "Bebidas",
    valor: 12000,
    promocion: "Refrescante granizado de sabores frutales",
    imagen: new URL('@/assets/iceeslush.jpg', import.meta.url).href,
  },
  {
    id: 13,
    nombre: "Gaseosa Grande",
    tipo: "Bebidas",
    valor: 11000,
    promocion: "Bebida grande de tu preferencia",
    imagen: new URL('@/assets/gaseosagrande.jpg', import.meta.url).href,
  },
  {
    id: 14,
    nombre: "Gaseosa Mediana",
    tipo: "Bebidas",
    valor: 9000,
    promocion: "Bebida mediana de tu preferencia",
    imagen: new URL('@/assets/gaseosamediana.jpg', import.meta.url).href,
  },
  {
    id: 15,
    nombre: "Gaseosa Pequeña",
    tipo: "Bebidas",
    valor: 7000,
    promocion: "Bebida pequeña para acompañar tu snack",
    imagen: new URL('@/assets/gaseosapequeña.jpg', import.meta.url).href,
  },
  {
    id: 16,
    nombre: "Leche Condensada",
    tipo: "Bebidas",
    valor: 3000,
    promocion: "Topping dulce para tus crispetas o postres",
    imagen: new URL('@/assets/lechecondensada.jpg', import.meta.url).href,
  },

  //  SNACKS
  {
    id: 17,
    nombre: "Nachos",
    tipo: "Snacks",
    valor: 10000,
    promocion: "Nachos con queso o guacamole",
    imagen: new URL('@/assets/nachos.jpg', import.meta.url).href,
  },
  {
    id: 18,
    nombre: "Perro Caliente",
    tipo: "Snacks",
    valor: 12000,
    promocion: "Perro caliente con papas y salsas al gusto",
    imagen: new URL('@/assets/perrocaliente.jpg', import.meta.url).href,
  },
  {
    id: 19,
    nombre: "De Todito",
    tipo: "Snacks",
    valor: 8000,
    promocion: "Mezcla crujiente de papas y platanitos",
    imagen: new URL('@/assets/detodito.jpg', import.meta.url).href,
  },
  {
    id: 20,
    nombre: "Doritos",
    tipo: "Snacks",
    valor: 8000,
    promocion: "Doritos sabor queso para disfrutar en la función",
    imagen: new URL('@/assets/doritos.jpeg', import.meta.url).href,
  },
  {
    id: 21,
    nombre: "Papa Margarita",
    tipo: "Snacks",
    valor: 7000,
    promocion: "Papas clásicas en su empaque original",
    imagen: new URL('@/assets/papasmargarita.jpg', import.meta.url).href,
  }
];
