export const peliculas = [
  {
    id: 1,
    titulo: "Demon Slayer: Kimetsu no Yaiba – To the Hashira Training",
    imagen: new URL('@/assets/demon.jpg', import.meta.url).href,
    reparto: "Natsuki Hanae, Akari Kitō, Hiro Shimono",
    sinopsis:
      "Tanjiro y sus amigos comienzan un intenso entrenamiento con los Pilares, los espadachines más poderosos del Cuerpo de Cazadores de Demonios, en preparación para la inevitable batalla contra Muzan Kibutsuji.",
    clasificacion: "PG-13",
    fechaEstreno: "2025-10-18",
    estado: "estreno",
    horarios: ["12:30", "15:00", "17:45", "20:30"],
    formatos: { es2D: true, es3D: false, doblada: true, dbox: true },
    tiposSala: ["D-BOX", "XD"],
    disponibilidadSillas: 74,
  },
  {
    id: 2,
    titulo: "Toy Story",
    imagen: new URL('@/assets/toy.jpg', import.meta.url).href,
    reparto: "Tom Hanks, Tim Allen, Annie Potts",
    sinopsis:
      "Woody, un muñeco vaquero, se siente amenazado cuando un nuevo juguete llamado Buzz Lightyear llega a la habitación de su dueño Andy.",
    clasificacion: "G",
    fechaEstreno: "1995-11-22",
    estado: "estreno",
    horarios: ["11:00", "13:30", "16:00", "18:30"],
    formatos: { es2D: true, es3D: true, doblada: true, dbox: false },
    tiposSala: ["XD", "Premier"],
    disponibilidadSillas: 90,
  },
  {
    id: 3,
    titulo: "El Conjuro 4: Último Rito",
    imagen: new URL('@/assets/conjuro.jpg', import.meta.url).href,
    reparto: "Vera Farmiga, Patrick Wilson, Sterling Jerins",
    sinopsis:
      "Los Warren enfrentan uno de los casos más oscuros de su carrera, cuando un antiguo demonio los lleva al límite de su fe y su amor.",
    clasificacion: "R",
    fechaEstreno: "2025-09-12",
    estado: "estreno",
    horarios: ["14:00", "16:30", "19:00", "21:30"],
    formatos: { es2D: true, es3D: false, doblada: true, dbox: true },
    tiposSala: ["D-BOX", "Premier"],
    disponibilidadSillas: 62,
  },
  {
    id: 4,
    titulo: "Mascotas al Rescate",
    imagen: new URL('@/assets/mascotas.jpg', import.meta.url).href,
    reparto: "Kevin Hart, Tiffany Haddish, Jenny Slate",
    sinopsis:
      "Un grupo de mascotas callejeras se une para salvar a los animales de un laboratorio secreto y encontrar un nuevo hogar.",
    clasificacion: "PG",
    fechaEstreno: "2025-10-05",
    estado: "estreno",
    horarios: ["10:30", "13:00", "15:30", "18:00"],
    formatos: { es2D: true, es3D: true, doblada: true, dbox: false },
    tiposSala: ["XD"],
    disponibilidadSillas: 80,
  },
  {
    id: 5,
    titulo: "Los Tipos Malos 2",
    imagen: new URL('@/assets/malos.jpg', import.meta.url).href,
    reparto: "Sam Rockwell, Awkwafina, Marc Maron",
    sinopsis:
      "Después de reformarse, el grupo de villanos animales debe volver a la acción para detener a un nuevo criminal que amenaza con destruir la ciudad.",
    clasificacion: "PG",
    fechaEstreno: "2025-08-22",
    estado: "estreno",
    horarios: ["12:00", "14:45", "17:30", "20:15"],
    formatos: { es2D: true, es3D: true, doblada: true, dbox: true },
    tiposSala: ["XD", "D-BOX"],
    disponibilidadSillas: 76,
  },
  {
    id: 6,
    titulo: "Otro Viernes de Locos",
    imagen: new URL('@/assets/viernes.jpg', import.meta.url).href,
    reparto: "Jamie Lee Curtis, Lindsay Lohan",
    sinopsis:
      "Madre e hija intercambian cuerpos una vez más, enfrentando los retos modernos de la familia, el trabajo y la tecnología.",
    clasificacion: "PG-13",
    fechaEstreno: "2025-07-15",
    estado: "estreno",
    horarios: ["11:30", "14:00", "16:30", "19:00"],
    formatos: { es2D: true, es3D: false, doblada: true, dbox: false },
    tiposSala: ["Premier"],
    disponibilidadSillas: 88,
  },
  {
    id: 7,
    titulo: "David Gilmour: Live in Pompeii",
    imagen: new URL('@/assets/david.jpeg', import.meta.url).href,
    reparto: "David Gilmour, Steve DiStanislao, Phil Manzanera",
    sinopsis:
      "El legendario guitarrista de Pink Floyd ofrece un concierto histórico en el anfiteatro de Pompeya, 45 años después del icónico show de la banda.",
    clasificacion: "PG",
    fechaEstreno: "2017-09-13",
    estado: "preventa",
    horarios: ["18:00", "20:30"],
    formatos: { es2D: true, es3D: false, doblada: false, dbox: false },
    tiposSala: ["Movie Bistro"],
    disponibilidadSillas: 70,
  },
  {
    id: 8,
    titulo: "Antes del Amanecer",
    imagen: new URL('@/assets/amanecer.jpeg', import.meta.url).href,
    reparto: "Ethan Hawke, Julie Delpy",
    sinopsis:
      "Dos jóvenes se conocen en un tren y pasan una noche entera en Viena, hablando sobre la vida, el amor y el destino.",
    clasificacion: "R",
    fechaEstreno: "1995-01-27",
    estado: "preventa",
    horarios: ["16:00", "18:30"],
    formatos: { es2D: true, es3D: false, doblada: false, dbox: false },
    tiposSala: ["Premier"],
    disponibilidadSillas: 60,
  },
  {
    id: 9,
    titulo: "Antes del Atardecer",
    imagen: new URL('@/assets/atardecer.jpeg', import.meta.url).href,
    reparto: "Ethan Hawke, Julie Delpy",
    sinopsis:
      "Nueve años después de su encuentro en Viena, Jesse y Céline se reencuentran en París, enfrentando los efectos del tiempo y las decisiones de la vida.",
    clasificacion: "R",
    fechaEstreno: "2004-07-02",
    estado: "preventa",
    horarios: ["17:00", "19:30"],
    formatos: { es2D: true, es3D: false, doblada: false, dbox: false },
    tiposSala: ["Premier"],
    disponibilidadSillas: 58,
  },
  {
    id: 10,
    titulo: "Epilogue",
    imagen: new URL('@/assets/epilogue.jpeg', import.meta.url).href,
    reparto: "Ethan Hawke, Julie Delpy",
    sinopsis:
      "La conclusión de una historia que exploró el amor a través de tres décadas. Jesse y Céline se enfrentan a lo que realmente significa envejecer juntos.",
    clasificacion: "R",
    fechaEstreno: "2025-09-05",
    estado: "preventa",
    horarios: ["18:15", "20:45"],
    formatos: { es2D: true, es3D: false, doblada: false, dbox: false },
    tiposSala: ["Premier"],
    disponibilidadSillas: 52,
  },
  {
    id: 11,
    titulo: "Diario de una Pasión",
    imagen: new URL('@/assets/pasion.jpeg', import.meta.url).href,
    reparto: "Ryan Gosling, Rachel McAdams",
    sinopsis:
      "Una historia de amor eterno entre dos jóvenes de diferentes clases sociales que luchan contra las circunstancias para estar juntos.",
    clasificacion: "PG-13",
    fechaEstreno: "2004-06-25",
    estado: "preventa",
    horarios: ["14:30", "17:00", "19:30"],
    formatos: { es2D: true, es3D: false, doblada: true, dbox: false },
    tiposSala: ["Premier"],
    disponibilidadSillas: 73,
  },
  {
    id: 12,
    titulo: "La Novia Rebelde",
    imagen: new URL('@/assets/novicia.jpeg', import.meta.url).href,
    reparto: "Julie Andrews, Christopher Plummer",
    sinopsis:
      "Una institutriz alegre transforma la vida de un estricto capitán de la marina y sus siete hijos en la Austria previa a la Segunda Guerra Mundial.",
    clasificacion: "G",
    fechaEstreno: "1965-03-02",
    estado: "preventa",
    horarios: ["13:00", "16:30"],
    formatos: { es2D: true, es3D: false, doblada: true, dbox: false },
    tiposSala: ["Movie Bistro"],
    disponibilidadSillas: 65,
  },
  {
    id: 13,
    titulo: "Una Batalla Tras Otra",
    imagen: new URL('@/assets/batallatras.jpeg', import.meta.url).href,
    reparto: "Chris Hemsworth, Emily Blunt, Idris Elba",
    sinopsis:
      "Una intensa historia de acción militar donde un escuadrón de élite debe detener una conspiración internacional antes de que sea demasiado tarde.",
    clasificacion: "R",
    fechaEstreno: "2025-11-01",
    estado: "preventa",
    horarios: ["15:00", "17:45", "20:30"],
    formatos: { es2D: true, es3D: true, doblada: true, dbox: true },
    tiposSala: ["D-BOX", "XD"],
    disponibilidadSillas: 68,
  },
  {
    id: 14,
    titulo: "TRON: Ares",
    imagen: new URL('@/assets/tron.jpg', import.meta.url).href,
    reparto: "Jared Leto, Greta Lee, Evan Peters",
    sinopsis:
      "Un nuevo programa digital cobra vida dentro de la red y debe enfrentarse a las consecuencias del mundo humano en el universo TRON.",
    clasificacion: "PG-13",
    fechaEstreno: "2025-12-12",
    estado: "estreno",
    horarios: ["14:15", "17:00", "19:45", "22:30"],
    formatos: { es2D: true, es3D: true, doblada: true, dbox: true },
    tiposSala: ["D-BOX", "XD", "Premier"],
    disponibilidadSillas: 80,
  },
];
